## rust-dap for rusty-probe
# usb_vid = "1209"
# usb_pid = "4853"
# serial = "dc61cd078f743b33ef4014"

[default.probe]
protocol = "Swd"
speed = 20000

[default.flashing]
enabled = true

[default.reset]
enabled = true
halt_afterwards = false

[default.general]
chip = "RP2040"
log_level = "WARN"
connect_under_reset = false